# Medication Dosage Monitor Exercises

Based on what you have learnt so far, these are three exercises with a medication dosage monitoring scenario. Each exercise processes patient data (name, age, weight, and dosage records with time and dose in mg) and applies weight-based and age-based safe dose ranges. The safe dose range is:
- **Adults (age ≥ 18)**: 0.1–0.5 mg/kg
- **Pediatrics (age < 18)**: 0.05–0.3 mg/kg

The exercises increase in difficulty, building on each other with validation, alerts, averages, risk assessment, and exception handling.


NOTE: Only Exercise 1 is considered as graded assignment. The other two are the materials for the upcoming session. 

## Exercise 1: Basic Dosage Safety Check for Multiple Patients

**Problem**: Validate medication dosages for multiple patients. Each patient has a name, age, weight (kg), and a list of dosage records (time, dose in mg). The program should:
- Calculate the safe dose range based on age and weight.
- Check if each dose is Safe (within range), Unsafe (outside range), or Invalid (≤ 0).
- Print each patient’s dosage status and the total number of valid doses.

**Sample Input**:
```python
patients = [
    {
        'name': 'Alice', 
        'age': 30, 
        'weight': 60, 
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40}
        ]
    },
    {
        'name': 'Bob', 
        'age': 16, 
        'weight': 40, 
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': -5}
        ]
    }
]
```

**Expected Output**:
```
Alice (Age: 30, Weight: 60 kg, Safe Range: 6.0–30.0 mg):
  08:00: Dose=10 mg - Safe
  12:00: Dose=40 mg - Unsafe
  Total valid doses: 2
Bob (Age: 16, Weight: 40 kg, Safe Range: 2.0–12.0 mg):
  08:00: Dose=5 mg - Safe
  Invalid dose at 12:00: Dose must be positive.
  Total valid doses: 1
```

In [2]:
patients = [
    {
        'name': 'Alice', 
        'age': 30, 
        'weight': 60, 
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40}
        ]
    },
    {
        'name': 'Bob', 
        'age': 16, 
        'weight': 40, 
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': -5}
        ]
    }
]



for patient in patients:
    name = patient.get('name')
    age = patient.get('age')
    weight = patient.get('weight')
    dosages = patient.get('dosages', [])

    if age >= 18:
        min_dose = 0.1 * weight
        max_dose = 0.5 * weight
    else:
        min_dose = 0.05 * weight
        max_dose = 0.3 * weight

    print(f"{name} (Age: {age}, Weight: {weight} kg, Safe Range: {min_dose:.1f}–{max_dose:.1f} mg):")

    valid_dose_count = 0
    for entry in dosages:
        time = entry.get('time')
        dose = entry.get('dose')

        if dose is None or dose <= 0:
            print(f"  Invalid dose at {time}: Dose must be positive.")
            continue

        valid_dose_count += 1
        if min_dose <= dose <= max_dose:
            status = "Safe"
        else:
            status = "Unsafe"
        print(f"  {time}: Dose={dose} mg - {status}")

    print(f"  Total valid doses: {valid_dose_count}")

Alice (Age: 30, Weight: 60 kg, Safe Range: 6.0–30.0 mg):
  08:00: Dose=10 mg - Safe
  12:00: Dose=40 mg - Unsafe
  Total valid doses: 2
Bob (Age: 16, Weight: 40 kg, Safe Range: 2.0–12.0 mg):
  08:00: Dose=5 mg - Safe
  Invalid dose at 12:00: Dose must be positive.
  Total valid doses: 1


## Exercise 2: Dosage Alerts and Average Calculation with Age-Based Rules

**Problem**: Extend the program to issue alerts for unsafe doses and calculate the average dose per patient. The program should:
- Calculate the safe dose range (0.1–0.5 mg/kg for age ≥ 18; 0.05–0.3 mg/kg for age < 18).
- Validate doses: Safe, Unsafe, or Invalid (≤ 0).
- Store times of unsafe doses for alerts.
- Calculate the average dose for valid doses per patient.
- Print each patient’s dosage status, unsafe dose alerts, and average dose.

**Sample Input**:
```python
patients = [
    {
        'name': 'Alice', 
        'age': 30, 
        'weight': 60, 
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40},
            {'time': '16:00', 'dose': 15}
        ]
    },
    {
        'name': 'Bob', 
        'age': 16, 
        'weight': 40, 
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': 15}
        ]
    }
]
```

**Expected Output**:
```
Alice (Age: 30, Weight: 60 kg, Safe Range: 6.0–30.0 mg):
  08:00: Dose=10 mg - Safe
  12:00: Dose=40 mg - Unsafe
  16:00: Dose=15 mg - Safe
  Alert: Unsafe dose detected at 12:00
  Average dose: 21.7 mg
Bob (Age: 16, Weight: 40 kg, Safe Range: 2.0–12.0 mg):
  08:00: Dose=5 mg - Safe
  12:00: Dose=15 mg - Unsafe
  Alert: Unsafe dose detected at 12:00
  Average dose: 10.0 mg
```

In [ ]:
patients = [
    {
        'name': 'Alice', 
        'age': 30, 
        'weight': 60, 
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40},
            {'time': '16:00', 'dose': 15}
        ]
    },
    {
        'name': 'Bob', 
        'age': 16, 
        'weight': 40, 
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': 15}
        ]
    }
]

for patient in patients:
    name = patient['name']
    age = patient['age']
    weight = patient['weight']
    dosages = patient['dosages']


    if age >= 18:
        min_dose = 0.1 * weight
        max_dose = 0.5 * weight
    else:
        min_dose = 0.05 * weight
        max_dose = 0.3 * weight

    print(f"{name} (Age: {age}, Weight: {weight} kg, Safe Range: {min_dose:.1f}–{max_dose:.1f} mg):")

    unsafe_times = []        
    valid_doses = []    

    for entry in dosages:
        time = entry['time']
        dose = entry['dose']

        if dose is None or dose <= 0:
            print(f"  Invalid dose at {time}: Dose must be positive.")
            continue

        valid_doses.append(dose)
        if min_dose <= dose <= max_dose:
            status = "Safe"
        else:
            status = "Unsafe"
            unsafe_times.append(time)

        print(f"  {time}: Dose={dose} mg - {status}")


    for t in unsafe_times:
        print(f"  Alert: Unsafe dose detected at {t}")


    if valid_doses:
        avg = sum(valid_doses) / len(valid_doses)
        print(f"  Average dose: {avg:.1f} mg")
    else:
        print("  No valid doses recorded.")


## Exercise 3: Dosage Risk Assessment and Distribution with Exception Handling

**Problem**: Extend the program to assess patient risk, analyze dosage status distribution, and handle exceptions robustly. The program should:
- Calculate the safe dose range (0.1–0.5 mg/kg for age ≥ 18; 0.05–0.3 mg/kg for age < 18).
- Validate doses: Safe, Unsafe, or Invalid (≤ 0).
- Flag patients as 'High Risk' if they have 2 or more unsafe doses or if their average dose exceeds the safe range.
- Calculate the distribution of Safe and Unsafe doses (percentage of valid doses) per patient.
- Handle exceptions (e.g., missing keys, invalid data types).
- Print each patient’s dosage status, risk assessment, and distribution.

**Sample Input**:
```python
patients = [
    {
        'name': 'Alice', 
        'age': 30, 
        'weight': 60, 
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40},
            {'time': '16:00', 'dose': 35}
        ]
    },
    {
        'name': 'Bob', 
        'age': 16, 
        'weight': 40, 
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': 15},
            {'time': '16:00', 'dose': 'invalid'}
        ]
    }
]
```

**Expected Output**:
```
Alice (Age: 30, Weight: 60 kg, Safe Range: 6.0–30.0 mg):
  08:00: Dose=10 mg - Safe
  12:00: Dose=40 mg - Unsafe
  16:00: Dose=35 mg - Unsafe
  Risk Status: High Risk (2 unsafe doses)
  Distribution: Safe: 1 (33.3%), Unsafe: 2 (66.7%)
Bob (Age: 16, Weight: 40 kg, Safe Range: 2.0–12.0 mg):
  08:00: Dose=5 mg - Safe
  12:00: Dose=15 mg - Unsafe
  Error at 16:00: Invalid dose value (non-numeric).
  Risk Status: Low
  Distribution: Safe: 1 (50.0%), Unsafe: 1 (50.0%)
```

In [3]:
patients = [
    {
        'name': 'Alice',
        'age': 30,
        'weight': 60,
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40},
            {'time': '16:00', 'dose': 35}
        ]
    },
    {
        'name': 'Bob',
        'age': 16,
        'weight': 40,
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': 15},
            {'time': '16:00', 'dose': 'invalid'}
        ]
    }
]

for patient in patients:
    try:
        name = patient['name']
        age = patient['age']
        weight = patient['weight']
        dosages = patient['dosages']
    except KeyError as e:
        print(f"Error: Missing key {e} in patient data.")
        continue


    try:
        age = float(age)
        weight = float(weight)
    except Exception:
        print(f"{name}: Error: Age or weight is not valid number.")
        continue


    if age >= 18:
        min_dose = 0.1 * weight
        max_dose = 0.5 * weight
    else:
        min_dose = 0.05 * weight
        max_dose = 0.3 * weight

    print(f"{name} (Age: {int(age)}, Weight: {int(weight)} kg, Safe Range: {min_dose:.1f}–{max_dose:.1f} mg):")


    safe_count = 0
    unsafe_count = 0
    valid_doses = []
    total_valid = 0

    for entry in dosages:
        try:
            time = entry['time']
            dose = entry['dose']
        except KeyError as e:
            print(f"  Error: Missing key {e} in dosage entry.")
            continue

        try:
            dose_val = float(dose)
        except Exception:
            print(f"  Error at {time}: Invalid dose value (non-numeric).")
            continue

        if dose_val <= 0:
            print(f"  {time}: Dose={dose} mg - Invalid")
            continue

        total_valid += 1
        valid_doses.append(dose_val)

        if min_dose <= dose_val <= max_dose:
            print(f"  {time}: Dose={int(dose_val) if dose_val.is_integer() else dose_val} mg - Safe")
            safe_count += 1
        else:
            print(f"  {time}: Dose={int(dose_val) if dose_val.is_integer() else dose_val} mg - Unsafe")
            unsafe_count += 1

    is_high_risk = False
    risk_cause = ""

    if unsafe_count >= 2:
        is_high_risk = True
        risk_cause = f"({unsafe_count} unsafe doses)"
    elif valid_doses:
        avg_dose = sum(valid_doses) / len(valid_doses)
        if avg_dose < min_dose or avg_dose > max_dose:
            is_high_risk = True
            risk_cause = "(average dose out of safe range)"
            
    if is_high_risk:
        print(f"  Risk Status: High Risk {risk_cause}")
    else:
        print("  Risk Status: Low")
    if total_valid > 0:
        safe_percent = 100 * safe_count / total_valid
        unsafe_percent = 100 * unsafe_count / total_valid
        print(f"  Distribution: Safe: {safe_count} ({safe_percent:.1f}%), Unsafe: {unsafe_count} ({unsafe_percent:.1f}%)")
    else:
        print("  Distribution: No valid doses.")


Alice (Age: 30, Weight: 60 kg, Safe Range: 6.0–30.0 mg):
  08:00: Dose=10 mg - Safe
  12:00: Dose=40 mg - Unsafe
  16:00: Dose=35 mg - Unsafe
  Risk Status: High Risk (2 unsafe doses)
  Distribution: Safe: 1 (33.3%), Unsafe: 2 (66.7%)
Bob (Age: 16, Weight: 40 kg, Safe Range: 2.0–12.0 mg):
  08:00: Dose=5 mg - Safe
  12:00: Dose=15 mg - Unsafe
  Error at 16:00: Invalid dose value (non-numeric).
  Risk Status: Low
  Distribution: Safe: 1 (50.0%), Unsafe: 1 (50.0%)
